---
name: Generate PingCastle XSD and create PR

on:
  workflow_dispatch:

jobs:
  generate-xsd:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
    env:
      PINGCASTLE_ZIP_URL: https://github.com/netwrix/pingcastle/releases/download/3.3.0.1/PingCastle_3.3.0.1.zip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main  # или staging — основная ветка

      - name: Configure Git
        run: |
          sudo apt update
          sudo apt install -y mono-complete wget jq zip dotnet-sdk-8.0 

      - name: Download PingCastle
        run: |
          wget -O PingCastle.zip "${PINGCASTLE_ZIP_URL}"
          unzip PingCastle.zip
          dotnet new console -o generate-pingcastle-xml
          cp Program.cs generate-pingcastle-xml

      - run: |
          dotnet build
          dotnet run -- --program ../PingCastle.exe --output ../pingcastle.xml --seed 100  --items-per-list 2
        working-directory: generate-pingcastle-xml

      - name: Check for changes
        id: diff
        run: |
          git add pingcastle.xml
          if git diff --cached --quiet; then
            echo "changed=false" >> $env:GITHUB_OUTPUT
          else
            echo "changed=true" >> $env:GITHUB_OUTPUT

      - name: Commit, push and create PR
        if: steps.diff.outputs.changed == 'true'
        run: |
          $date = Get-Date -Format "yyyyMMdd-HHmmss"
          $branch = "feature/pingcastle-xsd/$date"
          git checkout -b $branch
          git commit -m "Update PingCastle XSD [$date]"
          git push origin $branch

          gh pr create `
            --title "Update PingCastle XSD [$date]" `
            --body "Auto-generated XSD from PingCastle.exe" `
            --base staging `
            --head $branch
