---
name: Generate PingCastle XSD and create PR

on:
  workflow_dispatch:
defaults:
  run:
    working-directory: bishop_data/schemas

jobs:
  generate-xsd:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
    env:
      PINGCASTLE_ZIP_URL: https://github.com/netwrix/pingcastle/releases/download/3.3.0.1/PingCastle_3.3.0.1.zip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Configure Git
        run: |
          sudo apt update
          sudo apt install -y mono-complete wget jq zip dotnet-sdk-8.0

      - name: Download PingCastle
        run: |
          mkdir -p "$RUNNER_TEMP/pingcastle"
          wget -O "$RUNNER_TEMP/PingCastle.zip" "${PINGCASTLE_ZIP_URL}"
          unzip "$RUNNER_TEMP/PingCastle.zip" -d "$RUNNER_TEMP/pingcastle"
          dotnet new console -o $RUNNER_TEMP/program
          cp pingcastle/Program.cs  $RUNNER_TEMP/program

      - run: |
          dotnet build
          dotnet run -- --program ../pingcastle/PingCastle.exe \
            --output pingcastle.xml --seed 100  --items-per-list 2
        working-directory: $RUNNER_TEMP/program

      - run: |
          cp $RUNNER_TEMP/generate-pingcastle-xml/pingcastle.xml \
            pingcastle/pingcastle.xml
          ls -l pingcastle
          git diff
