---
name: Generate PingCastle XSD and create PR

on:
  workflow_dispatch:

jobs:
  generate-xsd:
    runs-on: windows-latest

    permissions:
      contents: write
      pull-requests: write
    env:
      PINGCASTLE_ZIP_URL: https://github.com/netwrix/pingcastle/releases/download/3.3.0.1/PingCastle_3.3.0.1.zip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main  # или staging — основная ветка

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Download PingCastle
        run: |
          Invoke-WebRequest -Uri $env:PINGCASTLE_ZIP_URL -OutFile PingCastle.zip
          Expand-Archive -Path PingCastle.zip -DestinationPath pingcastle

      - name: Generate XSD using xsd.exe
        run: |
          $xsdTool = "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\xsd.exe"
          & "$xsdTool" ".\pingcastle\PingCastle.exe" /type:PingCastle.Healthcheck.HealthcheckData

      - name: Move generated file
        run: |
          mkdir schemas -Force
          Move-Item -Path ".\PingCastle.Healthcheck.HealthcheckData.xsd" -Destination "schemas/PingCastle.xsd" -Force

      - name: Check for changes
        id: diff
        run: |
          git add schemas/PingCastle.xsd
          if git diff --cached --quiet; then
            echo "changed=false" >> $env:GITHUB_OUTPUT
          else
            echo "changed=true" >> $env:GITHUB_OUTPUT

      - name: Commit, push and create PR
        if: steps.diff.outputs.changed == 'true'
        run: |
          $date = Get-Date -Format "yyyyMMdd-HHmmss"
          $branch = "feature/pingcastle-xsd/$date"
          git checkout -b $branch
          git commit -m "Update PingCastle XSD [$date]"
          git push origin $branch

          gh pr create `
            --title "Update PingCastle XSD [$date]" `
            --body "Auto-generated XSD from PingCastle.exe" `
            --base staging `
            --head $branch
